[package]
name = "sgl"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.12"
futures = "0.3"
log = "0.4"
thiserror = "1.0"
wgpu = "0.14"
winit = "0.27"

[[example]]
name = "sandbox"
path = "sandbox/src/main.rs"
